spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/mynewdb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  application:
    name: Library
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass
    template:
      default-receive-timeout: 10000
