server:
  port: 8761
  enableSelfPreservation: false
spring:
  application:
    name: EurekaServer

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/
#  renewalPercentThreshold: 0.85
#  server:
#    enableSelfPreservation: false