server:
  port: 8765

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: NoteController
          uri: http://localhost:8080/
          predicates:
            - Path=/notes/**
